[tool.poetry]
name = "django-project"
version = "0.1.0"
description = ""
authors = ["Denis <gruyanov19962010@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django-phonenumber-field = { extras = ["phonenumbers"], version = "^8.1.0" }
django-countries = "^7.6.1"
django = "4.2.2"
redis = "^5.2.1"


[tool.poetry.group.dev.dependencies]
psycopg2 = "^2.9.10"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.0.1"
ipython = "^9.0.2"
black = "^25.1.0"
pillow = "^11.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
