# Generated by Django 4.2.2 on 2025-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_published",
            field=models.CharField(
                choices=[
                    ("moderation", "На модерации"),
                    ("published", "Опубликовано"),
                    ("unpublished", "Снято с публикации"),
                    ("archived", "В архиве"),
                ],
                default="moderation",
                help_text="Выберите статус публикации",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
