# Generated by Django 4.2.2 on 2025-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="temp-slug", max_length=100, unique=True),
        ),
    ]
